import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';

import "./globals.css";
import NextTopLoader from 'nextjs-toploader'; // en el layout principal

const inter = Inter({ subsets: ["latin"] });

import BootstrapClient from "./components/BootstrapClient";
import Header from "./components/Header";
import Footer from "./components/Footer";
export const metadata = {
  title: "Taller 04",
  description: "Generated by create next app",
};
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="es">
      <BootstrapClient/>
      <body className={`bg-fondo text-white-50 ${inter.className}`}>
      
        <Header/>
        <main>

        <NextTopLoader />  
        <SignedOut>
      <SignInButton />
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
        <NextTopLoader />
        {children}
        </main>
        
        <Footer/>

      </body>
    </html>
    </ClerkProvider>
  );
}
